name: default_connector
description: Generated Firebase Data Connect SDK for default connector
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_data_connect: any

dev_dependencies:
  flutter_test:
    sdk: flutter
