version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: my-postgres-container
    restart: always
    environment:
      POSTGRES_DB: telegram_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 758205
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis_cache:
    image: redis/redis-stack-server:latest
    container_name: my-redis-container
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data: